src/act/python/install_act

Made ACT and Obabel compile without git.

---

src/act/python/xvgutils.py

Fixed missing argument to XvgDataSet.

---

src/act/alexandria/actmol.cpp
src/act/alexandria/compound_reader.cpp
src/act/alexandria/topology.cpp
src/act/basics/msg_handler.h

Updated some other messages and introduced new checks. Set the default logging level to Info (3)
Fixes #778
Part of #690

Fixed difficult to interpret error message.

---

.github/workflows/act-test.yml
src/act/alexandria/openmm_xml.cpp
src/act/alexandria/tests/refdata/OpenMMXmlTest_Acetone.xml
src/act/alexandria/tests/refdata/OpenMMXmlTest_AcetonePol.xml
src/act/alexandria/tests/refdata/OpenMMXmlTest_AcetonePolMDrude.xml
src/act/alexandria/tests/refdata/OpenMMXmlTest_Furan.xml
src/act/alexandria/tests/refdata/OpenMMXmlTest_FuranPol.xml
src/act/alexandria/tests/refdata/OpenMMXmlTest_FuranPolNoNum.xml
src/act/alexandria/tests/refdata/OpenMMXmlTest_Merged.xml
src/act/alexandria/tests/refdata/OpenMMXmlTest_Sulfate.xml
src/act/alexandria/tests/refdata/OpenMMXmlTest_SulfatePol.xml
src/act/utility/xml_util.cpp

Made nexcl the same everywhere in OpenMM output.

---

src/act/alexandria/openmm_xml.cpp
src/act/alexandria/topology.cpp
src/act/alexandria/topology.h

Replaced old debug stuff by MsgHandler
Part of #788
Part of #789

Working on solution for single particle vsite.

---

src/act/forcefield/forcefield_tables.cpp
src/act/forcefield/forcefield_tables.h
src/act/forcefield/merge_ff.cpp

Also made printing of sigma depend on number of FF files.
Fixes #790

Made printing of parameters with one FF file possible in merge_ff.

---

src/act/forcefield/forcefield_tables.cpp
src/act/forcefield/forcefield_tables.h

Fixed not-printing sigma and N

---

src/act/alexandria/train_ff.cpp
src/act/qgen/qgen_acm.cpp

Fixed a number of bugs handling incorrect input.

---

src/gromacs/utility/errorformat.cpp

Updated error message.

---

src/act/alexandria/topology.cpp

Made code work consistently for generating vsite1

---

src/act/alexandria/actmol.cpp
src/act/alexandria/actmol.h
src/act/alexandria/devcomputer.cpp
src/act/alexandria/min_complex.cpp
src/act/alexandria/secondvirial.cpp
src/act/alexandria/simulate.cpp
src/act/alexandria/train_utility.cpp
src/act/alexandria/train_utility.h
src/act/qgen/tests/interactionEnergyTest.cpp

Replaced debug statements by msghandler.

---

src/act/alexandria/actmol.cpp
src/act/qgen/tests/refdata/InteractionEnergyTest_AcetateWaterACSg.xml
src/act/qgen/tests/refdata/InteractionEnergyTest_AcetateWaterACSpg.xml
src/act/qgen/tests/refdata/InteractionEnergyTest_HydrogenFluorideDimerACSps.xml
src/act/qgen/tests/refdata/InteractionEnergyTest_MethanolWaterACSg.xml
src/act/qgen/tests/refdata/InteractionEnergyTest_MethanolWaterACSpg.xml
src/act/qgen/tests/refdata/InteractionEnergyTest_WaterDimerACSg.xml
src/act/qgen/tests/refdata/InteractionEnergyTest_WaterDimerACSpg.xml
src/act/qgen/tests/refdata/InteractionEnergyTest_WaterIodideACSg.xml
src/act/qgen/tests/refdata/InteractionEnergyTest_WaterIodideACSpg.xml

Swapped induction and induction correction terms.

---

src/act/alexandria/topology.cpp

Made checking for missing parameters more strict

---

src/act/forcefield/combruleutil.cpp
src/act/forcefield/gen_ff.cpp
src/act/forces/combinationrules.cpp

Implemented support for using Morse for induction correction.

---

src/act/alexandria/openmm_xml.cpp
src/act/forcefield/potential.cpp
src/act/forcefield/potential.h

Also starts to get rid of the parameter name mess due to atom parameters and pair parameters being mixed.
Part of #689
Fixes #851

Added support for Morse as induction correction.

---

src/act/alexandria/openmm_xml.cpp

Removed double CustomBondForce from openmm FFs.

---

src/act/alexandria/openmm_xml.cpp
src/act/python/act_openmm.py

More fixes to make OpenMM work with multiple potentials.

---

src/act/forcefield/gen_ff.cpp
src/act/python/actgui

Changes to gen_ff.cpp to not use vdwcorr and inductioncorrection unless explicitly specified.
Updates to make the gui more stable
Added option to set number of exclusions
Part of #869

Improvement to actgui

---

src/act/alexandria/train_ff.cpp

Reorganized WALL notification

---

src/act/python/actgui

More stuff to come.
Part of #869

Made FF generator just one module in the ACT gui.

---

src/act/forces/combinationrules.cpp

Modified implementation of Kronecker combination rule.

---

src/act/alexandria/optimizationindex.cpp
src/act/alexandria/staticindividualinfo.cpp

Corrected printing of final parameters after training.

---

src/act/alexandria/topology.cpp
src/act/alexandria/topology.h

Rewrote and simplified generating exclusions.

---

src/act/molprop/composition.cpp
src/act/molprop/molpropobservable.cpp
src/act/molprop/topologyentry.cpp
src/act/utility/communicationrecord.h

Replaced debug by msg_handler in large part of molprop dir.

---

src/act/forcefield/potential.cpp
src/act/forces/forcecomputerimpl.cpp

Fixed some typos related to SLATER_ISA_TT

---

share/alexandria.csv

Fixed bug in data file.

---

src/act/alexandria/gentop.cpp
src/act/alexandria/openmm_xml.cpp

Added possibility to not change masses of particles at all.
Fixes #955

Made handling of drude masses similar to OpenMM.

---

src/act/python/viewxvg

Fixed set extent issue

---

src/act/alexandria/topology.cpp
src/act/forces/tests/ACS-pg-vs2.xml
src/act/forces/tests/refdata/VsiteHandlerTest_VSite2HBr.xml
src/act/forces/tests/refdata/VsiteHandlerTest_VSite2HBrForce.xml
src/act/python/actgui

Made vsite1 depend on atom type instead of bond type.
